package xivvic.adt.pgraph.util.serdes;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import xivvic.adt.pgraph.util.serdes.Serde;

import static org.junit.Assert.*;

import org.apache.tinkerpop.gremlin.structure.Graph;
import org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph;

public class GraphSerdeDegenerateInputTest
{
    Serde subject;
    
//    @Before
//    public void before()
//    {
//    }
//    
 
    @Test
    public void onSerialize_withNullGraph_thenReturnZeroLengthArray() throws SerdeException
    {
	// Arrange
	//
	int  length = 0;
	
	// Act
	//
	byte[] have = Serde.serialize(null);
	
	// Assert
	//
	assertNotNull(have);
	assertEquals(length, have.length);
    }

    @Test
    public void onSerialize_withEmptyGraph_thenReturnZeroLengthArray() throws SerdeException
    {
	// Arrange
	//
	int  length = 0;
	Graph empty = TinkerGraph.open();
	
	// Act
	//
	byte[] have = Serde.serialize(empty);
	
	
	// Assert
	//
	assertNotNull(have);
	assertEquals(length, have.length);
    }
    
    @Test
    public void onDeserialize_withNullByteArray_thenReturnEmptyGraph() throws SerdeException
    {
	// Arrange
	//
	Object[] nothing = {};
	
	// Act
	//
	Graph g = Serde.deserialize(null);
	
	// Assert
	//
	assertNotNull(g);
	assertFalse(g.vertices(nothing).hasNext());
    }

    @Test
    public void onDeserialize_withZeroLengthByteArray_thenReturnEmptyGraph() throws SerdeException
    {
	// Arrange
	//
	byte[]     empty = {};
	Object[] nothing = {};
	
	// Act
	//
	Graph g = Serde.deserialize(empty);
	
	// Assert
	//
	assertNotNull(g);
	assertFalse(g.vertices(nothing).hasNext());
    }
      
}
