import com.google.protobuf.InvalidProtocolBufferException;

import src.main.proto.Foo;
import we.proto.util.ProtobufErrorElf;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Program {

    public static final void main(String[] args)
    {
	System.out.println("Going to create a foo");

	final Foo foo = Foo.newBuilder()
		.setBar("Jackapoo")
		.setBaz(100)
		.build();

	System.out.println("Back from creation");

	System.out.println(foo);
	System.out.println(foo.getDescriptorForType());

	final byte[] bs = foo.toByteArray();
	try
	{
	    final Foo hydrated = Foo.parseFrom(bs);
	    System.out.println(hydrated);
	} catch (final InvalidProtocolBufferException e)
	{
	    ProtobufErrorElf.displayError(e);
	}
    }

}
