import com.google.protobuf.InvalidProtocolBufferException;

import src.main.proto.Foo;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Program {
    
    public static final void main(String[] args)
    {
	System.out.println("Going to create a foo");
	
	Foo foo = Foo.newBuilder()
		.setBar("Jackapoo")
		.setBaz(100)
		.build();
	
	System.out.println("Back from creation");
	
	System.out.println(foo);
	System.out.println(foo.getDescriptorForType());
	
	byte[] bs = foo.toByteArray();
	try
	{
	    Foo hydrated = Foo.parseFrom(bs);
	    System.out.println(hydrated);
	} catch (InvalidProtocolBufferException e)
	{
	    // TODO Auto-generated catch block
	    e.printStackTrace();
	}
	
	
    }

}
